export interface GalleryImage {
  id: string
  venue: string
  city: string
  category: "weddings" | "corporate" | "decor" | "all"
  image: string
  title: string
  description: string
}

export const venues = [
  // Burton-on-Trent
  { name: "The Brewery Quarter", city: "Burton" },
  { name: "St. Paul's Church", city: "Burton" },

  // Derby
  { name: "Derby Cathedral", city: "Derby" },
  { name: "Darley Abbey", city: "Derby" },
  { name: "The Roundhouse", city: "Derby" },

  // Nottingham
  { name: "Nottingham Castle", city: "Nottingham" },
  { name: "Wollaton Hall", city: "Nottingham" },
  { name: "Trent Bridge", city: "Nottingham" },

  // Leicester
  { name: "Leicester Cathedral", city: "Leicester" },
  { name: "Belgrave Hall", city: "Leicester" },
  { name: "King Power Stadium", city: "Leicester" },

  // Birmingham
  { name: "Birmingham Town Hall", city: "Birmingham" },
  { name: "The Botanical Gardens", city: "Birmingham" },
  { name: "Library of Birmingham", city: "Birmingham" },
  { name: "Edgbaston Cricket Ground", city: "Birmingham" },
]

export const galleryImages: GalleryImage[] = [
  // The Brewery Quarter, Burton
  {
    id: "brewery-1",
    venue: "The Brewery Quarter",
    city: "Burton",
    category: "weddings",
    image: "/luxury-wedding-ceremony-at-historic-industrial-bre.jpg",
    title: "Historic Brewery Wedding",
    description: "Elegant ceremony at The Brewery Quarter",
  },
  {
    id: "brewery-2",
    venue: "The Brewery Quarter",
    city: "Burton",
    category: "corporate",
    image: "/corporate-gala-event-at-brewery-venue-with-industr.jpg",
    title: "Corporate Gala",
    description: "Professional event at The Brewery Quarter",
  },
  {
    id: "brewery-3",
    venue: "The Brewery Quarter",
    city: "Burton",
    category: "decor",
    image: "/elegant-table-settings-with-gold-accents-candles-a.jpg",
    title: "Industrial Elegance",
    description: "Sophisticated décor at The Brewery Quarter",
  },
  {
    id: "brewery-4",
    venue: "The Brewery Quarter",
    city: "Burton",
    category: "weddings",
    image: "/wedding-reception-with-fairy-lights-and-rustic-dec.jpg",
    title: "Rustic Romance",
    description: "Reception at The Brewery Quarter",
  },
  {
    id: "brewery-5",
    venue: "The Brewery Quarter",
    city: "Burton",
    category: "decor",
    image: "/dramatic-tall-floral-centerpieces-with-candles-and.jpg",
    title: "Dramatic Florals",
    description: "Stunning arrangements at The Brewery Quarter",
  },

  // St. Paul's Church, Burton
  {
    id: "stpauls-1",
    venue: "St. Paul's Church",
    city: "Burton",
    category: "weddings",
    image: "/traditional-church-wedding-ceremony-with-elegant-f.jpg",
    title: "Traditional Ceremony",
    description: "Classic wedding at St. Paul's Church",
  },
  {
    id: "stpauls-2",
    venue: "St. Paul's Church",
    city: "Burton",
    category: "weddings",
    image: "/church-aisle-decorated-with-white-flowers-and-cand.jpg",
    title: "Sacred Elegance",
    description: "Beautiful aisle décor at St. Paul's",
  },
  {
    id: "stpauls-3",
    venue: "St. Paul's Church",
    city: "Burton",
    category: "decor",
    image: "/church-altar-with-luxury-floral-arrangements-and-g.jpg",
    title: "Altar Arrangements",
    description: "Stunning florals at St. Paul's Church",
  },
  {
    id: "stpauls-4",
    venue: "St. Paul's Church",
    city: "Burton",
    category: "weddings",
    image: "/bride-and-groom-at-historic-church-entrance-with-c.jpg",
    title: "Grand Exit",
    description: "Celebration at St. Paul's Church",
  },
  {
    id: "stpauls-5",
    venue: "St. Paul's Church",
    city: "Burton",
    category: "weddings",
    image: "/church-wedding-with-string-quartet-musicians-and-e.jpg",
    title: "Musical Ceremony",
    description: "Live music at St. Paul's Church",
  },

  // Derby Cathedral
  {
    id: "derby-cathedral-1",
    venue: "Derby Cathedral",
    city: "Derby",
    category: "weddings",
    image: "/grand-cathedral-wedding-with-dramatic-gothic-archi.jpg",
    title: "Cathedral Grandeur",
    description: "Majestic wedding at Derby Cathedral",
  },
  {
    id: "derby-cathedral-2",
    venue: "Derby Cathedral",
    city: "Derby",
    category: "corporate",
    image: "/corporate-event-at-historic-cathedral-with-profess.jpg",
    title: "Corporate Excellence",
    description: "Business event at Derby Cathedral",
  },
  {
    id: "derby-cathedral-3",
    venue: "Derby Cathedral",
    city: "Derby",
    category: "decor",
    image: "/cathedral-decorated-with-tall-floral-columns-and-c.jpg",
    title: "Gothic Romance",
    description: "Dramatic décor at Derby Cathedral",
  },
  {
    id: "derby-cathedral-4",
    venue: "Derby Cathedral",
    city: "Derby",
    category: "weddings",
    image: "/cathedral-choir-performing-at-elegant-wedding-cere.jpg",
    title: "Choral Celebration",
    description: "Musical wedding at Derby Cathedral",
  },
  {
    id: "derby-cathedral-5",
    venue: "Derby Cathedral",
    city: "Derby",
    category: "weddings",
    image: "/cathedral-wedding-with-colorful-stained-glass-wind.jpg",
    title: "Stained Glass Beauty",
    description: "Illuminated ceremony at Derby Cathedral",
  },

  // Darley Abbey, Derby
  {
    id: "darley-1",
    venue: "Darley Abbey",
    city: "Derby",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Abbey Gardens",
    description: "Garden wedding at Darley Abbey",
  },
  {
    id: "darley-2",
    venue: "Darley Abbey",
    city: "Derby",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Marquee Elegance",
    description: "Luxury reception at Darley Abbey",
  },
  {
    id: "darley-3",
    venue: "Darley Abbey",
    city: "Derby",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Floral Arch",
    description: "Ceremony décor at Darley Abbey",
  },
  {
    id: "darley-4",
    venue: "Darley Abbey",
    city: "Derby",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Golden Hour",
    description: "Sunset celebration at Darley Abbey",
  },
  {
    id: "darley-5",
    venue: "Darley Abbey",
    city: "Derby",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Garden Party",
    description: "Corporate event at Darley Abbey",
  },

  // The Roundhouse, Derby
  {
    id: "roundhouse-1",
    venue: "The Roundhouse",
    city: "Derby",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Modern Corporate",
    description: "Business event at The Roundhouse",
  },
  {
    id: "roundhouse-2",
    venue: "The Roundhouse",
    city: "Derby",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Contemporary Wedding",
    description: "Modern celebration at The Roundhouse",
  },
  {
    id: "roundhouse-3",
    venue: "The Roundhouse",
    city: "Derby",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Dramatic Lighting",
    description: "Stunning ambiance at The Roundhouse",
  },
  {
    id: "roundhouse-4",
    venue: "The Roundhouse",
    city: "Derby",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Product Launch",
    description: "Corporate launch at The Roundhouse",
  },
  {
    id: "roundhouse-5",
    venue: "The Roundhouse",
    city: "Derby",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Dance Floor",
    description: "Reception party at The Roundhouse",
  },

  // Nottingham Castle
  {
    id: "nottingham-castle-1",
    venue: "Nottingham Castle",
    city: "Nottingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Castle Romance",
    description: "Royal wedding at Nottingham Castle",
  },
  {
    id: "nottingham-castle-2",
    venue: "Nottingham Castle",
    city: "Nottingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Prestigious Gala",
    description: "Corporate event at Nottingham Castle",
  },
  {
    id: "nottingham-castle-3",
    venue: "Nottingham Castle",
    city: "Nottingham",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Banquet Hall",
    description: "Elegant dining at Nottingham Castle",
  },
  {
    id: "nottingham-castle-4",
    venue: "Nottingham Castle",
    city: "Nottingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Castle Grounds",
    description: "Outdoor ceremony at Nottingham Castle",
  },
  {
    id: "nottingham-castle-5",
    venue: "Nottingham Castle",
    city: "Nottingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Medieval Elegance",
    description: "Historic reception at Nottingham Castle",
  },

  // Wollaton Hall, Nottingham
  {
    id: "wollaton-1",
    venue: "Wollaton Hall",
    city: "Nottingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Manor House Wedding",
    description: "Stately wedding at Wollaton Hall",
  },
  {
    id: "wollaton-2",
    venue: "Wollaton Hall",
    city: "Nottingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Executive Conference",
    description: "Business event at Wollaton Hall",
  },
  {
    id: "wollaton-3",
    venue: "Wollaton Hall",
    city: "Nottingham",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Garden Party Setup",
    description: "Outdoor elegance at Wollaton Hall",
  },
  {
    id: "wollaton-4",
    venue: "Wollaton Hall",
    city: "Nottingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Ballroom Splendor",
    description: "Grand reception at Wollaton Hall",
  },
  {
    id: "wollaton-5",
    venue: "Wollaton Hall",
    city: "Nottingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Architectural Beauty",
    description: "Portrait session at Wollaton Hall",
  },

  // Trent Bridge, Nottingham
  {
    id: "trent-bridge-1",
    venue: "Trent Bridge",
    city: "Nottingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Cricket Pavilion",
    description: "Corporate hospitality at Trent Bridge",
  },
  {
    id: "trent-bridge-2",
    venue: "Trent Bridge",
    city: "Nottingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Sports Venue Conference",
    description: "Business event at Trent Bridge",
  },
  {
    id: "trent-bridge-3",
    venue: "Trent Bridge",
    city: "Nottingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Unique Venue Wedding",
    description: "Distinctive celebration at Trent Bridge",
  },
  {
    id: "trent-bridge-4",
    venue: "Trent Bridge",
    city: "Nottingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Awards Ceremony",
    description: "Corporate awards at Trent Bridge",
  },
  {
    id: "trent-bridge-5",
    venue: "Trent Bridge",
    city: "Nottingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Networking Event",
    description: "Business networking at Trent Bridge",
  },

  // Leicester Cathedral
  {
    id: "leicester-cathedral-1",
    venue: "Leicester Cathedral",
    city: "Leicester",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Cathedral Wedding",
    description: "Traditional ceremony at Leicester Cathedral",
  },
  {
    id: "leicester-cathedral-2",
    venue: "Leicester Cathedral",
    city: "Leicester",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "White Rose Elegance",
    description: "Floral ceremony at Leicester Cathedral",
  },
  {
    id: "leicester-cathedral-3",
    venue: "Leicester Cathedral",
    city: "Leicester",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Corporate Service",
    description: "Formal event at Leicester Cathedral",
  },
  {
    id: "leicester-cathedral-4",
    venue: "Leicester Cathedral",
    city: "Leicester",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Seasonal Décor",
    description: "Beautiful arrangements at Leicester Cathedral",
  },
  {
    id: "leicester-cathedral-5",
    venue: "Leicester Cathedral",
    city: "Leicester",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Wedding Procession",
    description: "Grand entrance at Leicester Cathedral",
  },

  // Belgrave Hall, Leicester
  {
    id: "belgrave-1",
    venue: "Belgrave Hall",
    city: "Leicester",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Georgian Elegance",
    description: "Period wedding at Belgrave Hall",
  },
  {
    id: "belgrave-2",
    venue: "Belgrave Hall",
    city: "Leicester",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Vintage Garden Party",
    description: "Garden celebration at Belgrave Hall",
  },
  {
    id: "belgrave-3",
    venue: "Belgrave Hall",
    city: "Leicester",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Period Décor",
    description: "Historic styling at Belgrave Hall",
  },
  {
    id: "belgrave-4",
    venue: "Belgrave Hall",
    city: "Leicester",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Corporate Dinner",
    description: "Business dining at Belgrave Hall",
  },
  {
    id: "belgrave-5",
    venue: "Belgrave Hall",
    city: "Leicester",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Intimate Ceremony",
    description: "Private wedding at Belgrave Hall",
  },

  // King Power Stadium, Leicester
  {
    id: "king-power-1",
    venue: "King Power Stadium",
    city: "Leicester",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Stadium Corporate Event",
    description: "Major event at King Power Stadium",
  },
  {
    id: "king-power-2",
    venue: "King Power Stadium",
    city: "Leicester",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Stadium Conference",
    description: "Business conference at King Power Stadium",
  },
  {
    id: "king-power-3",
    venue: "King Power Stadium",
    city: "Leicester",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Sports Fan Wedding",
    description: "Themed wedding at King Power Stadium",
  },
  {
    id: "king-power-4",
    venue: "King Power Stadium",
    city: "Leicester",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Executive Hospitality",
    description: "VIP event at King Power Stadium",
  },
  {
    id: "king-power-5",
    venue: "King Power Stadium",
    city: "Leicester",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Team Building",
    description: "Corporate activity at King Power Stadium",
  },

  // Birmingham Town Hall
  {
    id: "bham-town-hall-1",
    venue: "Birmingham Town Hall",
    city: "Birmingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Town Hall Grandeur",
    description: "Prestigious wedding at Birmingham Town Hall",
  },
  {
    id: "bham-town-hall-2",
    venue: "Birmingham Town Hall",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Gala Evening",
    description: "Corporate gala at Birmingham Town Hall",
  },
  {
    id: "bham-town-hall-3",
    venue: "Birmingham Town Hall",
    city: "Birmingham",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Dramatic Décor",
    description: "Stunning styling at Birmingham Town Hall",
  },
  {
    id: "bham-town-hall-4",
    venue: "Birmingham Town Hall",
    city: "Birmingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Classical Ceremony",
    description: "Musical wedding at Birmingham Town Hall",
  },
  {
    id: "bham-town-hall-5",
    venue: "Birmingham Town Hall",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Awards Night",
    description: "Corporate awards at Birmingham Town Hall",
  },

  // The Botanical Gardens, Birmingham
  {
    id: "botanical-1",
    venue: "The Botanical Gardens",
    city: "Birmingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Garden Wedding",
    description: "Natural beauty at The Botanical Gardens",
  },
  {
    id: "botanical-2",
    venue: "The Botanical Gardens",
    city: "Birmingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Glasshouse Reception",
    description: "Unique venue at The Botanical Gardens",
  },
  {
    id: "botanical-3",
    venue: "The Botanical Gardens",
    city: "Birmingham",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Garden Party Décor",
    description: "Outdoor elegance at The Botanical Gardens",
  },
  {
    id: "botanical-4",
    venue: "The Botanical Gardens",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Summer Corporate Event",
    description: "Business event at The Botanical Gardens",
  },
  {
    id: "botanical-5",
    venue: "The Botanical Gardens",
    city: "Birmingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Romantic Portraits",
    description: "Photo session at The Botanical Gardens",
  },

  // Library of Birmingham
  {
    id: "library-bham-1",
    venue: "Library of Birmingham",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Modern Corporate",
    description: "Contemporary event at Library of Birmingham",
  },
  {
    id: "library-bham-2",
    venue: "Library of Birmingham",
    city: "Birmingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Literary Wedding",
    description: "Unique celebration at Library of Birmingham",
  },
  {
    id: "library-bham-3",
    venue: "Library of Birmingham",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Product Launch",
    description: "Corporate launch at Library of Birmingham",
  },
  {
    id: "library-bham-4",
    venue: "Library of Birmingham",
    city: "Birmingham",
    category: "decor",
    image: "/placeholder.svg?height=600&width=800",
    title: "Contemporary Styling",
    description: "Modern décor at Library of Birmingham",
  },
  {
    id: "library-bham-5",
    venue: "Library of Birmingham",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Rooftop Networking",
    description: "Business event at Library of Birmingham",
  },

  // Edgbaston Cricket Ground, Birmingham
  {
    id: "edgbaston-1",
    venue: "Edgbaston Cricket Ground",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Cricket Hospitality",
    description: "Corporate event at Edgbaston",
  },
  {
    id: "edgbaston-2",
    venue: "Edgbaston Cricket Ground",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Conference Venue",
    description: "Business conference at Edgbaston",
  },
  {
    id: "edgbaston-3",
    venue: "Edgbaston Cricket Ground",
    city: "Birmingham",
    category: "weddings",
    image: "/placeholder.svg?height=600&width=800",
    title: "Sports Venue Wedding",
    description: "Unique wedding at Edgbaston",
  },
  {
    id: "edgbaston-4",
    venue: "Edgbaston Cricket Ground",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Awards Dinner",
    description: "Corporate celebration at Edgbaston",
  },
  {
    id: "edgbaston-5",
    venue: "Edgbaston Cricket Ground",
    city: "Birmingham",
    category: "corporate",
    image: "/placeholder.svg?height=600&width=800",
    title: "Trade Exhibition",
    description: "Business expo at Edgbaston",
  },
]
